/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs/{run_id}/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Eval */
        get: operations["get_run_eval_api_runs__run_id__eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/souls/{soul_id}/eval/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Soul Eval History */
        get: operations["get_soul_eval_history_api_souls__soul_id__eval_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Logs */
        get: operations["get_run_logs_api_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Nodes */
        get: operations["get_run_nodes_api_runs__run_id__nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_api_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_workflows__id__get"];
        /** Update Workflow */
        put: operations["update_workflow_api_workflows__id__put"];
        post?: never;
        /** Delete Workflow */
        delete: operations["delete_workflow_api_workflows__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Workflow Enabled */
        patch: operations["set_workflow_enabled_api_workflows__id__enabled_patch"];
        trace?: never;
    };
    "/api/workflows/{id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Workflow */
        post: operations["commit_workflow_api_workflows__id__commits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workflow Simulation */
        post: operations["create_workflow_simulation_api_workflows__id__simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/souls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Souls */
        get: operations["list_souls_api_souls_get"];
        put?: never;
        /** Create Soul */
        post: operations["create_soul_api_souls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/souls/{id}/usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Soul Usages */
        get: operations["get_soul_usages_api_souls__id__usages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/souls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Soul */
        get: operations["get_soul_api_souls__id__get"];
        /** Update Soul */
        put: operations["update_soul_api_souls__id__put"];
        post?: never;
        /** Delete Soul */
        delete: operations["delete_soul_api_souls__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Steps */
        get: operations["list_steps_api_steps_get"];
        put?: never;
        /** Create Step */
        post: operations["create_step_api_steps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Step */
        get: operations["get_step_api_steps__id__get"];
        /** Update Step */
        put: operations["update_step_api_steps__id__put"];
        post?: never;
        /** Delete Step */
        delete: operations["delete_step_api_steps__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__id__get"];
        /** Update Task */
        put: operations["update_task_api_tasks__id__put"];
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_tasks__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_settings_providers_get"];
        put?: never;
        /** Create Provider */
        post: operations["create_provider_api_settings_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider */
        get: operations["get_provider_api_settings_providers__provider_id__get"];
        /** Update Provider */
        put: operations["update_provider_api_settings_providers__provider_id__put"];
        post?: never;
        /** Delete Provider */
        delete: operations["delete_provider_api_settings_providers__provider_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers/{provider_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider */
        post: operations["test_provider_api_settings_providers__provider_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider Credentials */
        post: operations["test_provider_credentials_api_settings_providers_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Model Defaults */
        get: operations["list_model_defaults_api_settings_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Model Default */
        put: operations["update_model_default_api_settings_models__model_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Budgets */
        get: operations["list_budgets_api_settings_budgets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Settings */
        get: operations["get_app_settings_api_settings_app_get"];
        /** Update App Settings */
        put: operations["update_app_settings_api_settings_app_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attention Items */
        get: operations["get_attention_items_api_dashboard_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Git Status */
        get: operations["git_status_api_git_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Git Commit */
        post: operations["git_commit_api_git_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Git Diff */
        get: operations["git_diff_api_git_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Git Log */
        get: operations["git_log_api_git_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/sim-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sim Branch */
        post: operations["create_sim_branch_api_git_sim_branch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_models_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description SSE endpoint that streams real-time execution events for a run.
         */
        get: operations["stream_run_events_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettingsOut */
        AppSettingsOut: {
            /** Base Path */
            base_path?: string | null;
            /** Default Provider */
            default_provider?: string | null;
            /** Auto Save */
            auto_save?: boolean | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Fallback Chain Enabled */
            fallback_chain_enabled?: boolean | null;
        };
        /** AttentionItem */
        AttentionItem: {
            /**
             * Type
             * @enum {string}
             */
            type: "assertion_regression" | "cost_spike" | "quality_drop" | "new_baseline";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Run Id */
            run_id: string;
            /** Workflow Id */
            workflow_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "info";
        };
        /** AttentionItemsResponse */
        AttentionItemsResponse: {
            /** Items */
            items: components["schemas"]["AttentionItem"][];
        };
        /** CanvasViewport */
        CanvasViewport: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Zoom
             * @default 1
             */
            zoom: number;
        };
        /** CommitEntry */
        CommitEntry: {
            /** Hash */
            hash: string;
            /** Message */
            message: string;
            /** Date */
            date: string;
            /** Author */
            author: string;
        };
        /** CommitRequest */
        CommitRequest: {
            /** Message */
            message: string;
            /** Files */
            files?: string[] | null;
        };
        /** CommitResponse */
        CommitResponse: {
            /** Hash */
            hash: string;
            /** Message */
            message: string;
        };
        /** DashboardKPIsResponse */
        DashboardKPIsResponse: {
            /** Runs Today */
            runs_today: number;
            /** Cost Today Usd */
            cost_today_usd: number;
            /** Eval Pass Rate */
            eval_pass_rate: number | null;
            /** Regressions */
            regressions: number | null;
            /**
             * Runs Previous Period
             * @default 0
             */
            runs_previous_period: number;
            /**
             * Cost Previous Period Usd
             * @default 0
             */
            cost_previous_period_usd: number;
            /** Eval Pass Rate Previous Period */
            eval_pass_rate_previous_period?: number | null;
            /** Regressions Previous Period */
            regressions_previous_period?: number | null;
            /**
             * Period Hours
             * @default 24
             */
            period_hours: number;
        };
        /** DiffResponse */
        DiffResponse: {
            /** Diff */
            diff: string;
        };
        /** EvalDelta */
        EvalDelta: {
            /** Cost Pct */
            cost_pct: number;
            /** Tokens Pct */
            tokens_pct: number;
            /** Score Delta */
            score_delta: number | null;
            /** Baseline Run Count */
            baseline_run_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelDefaultUpdate */
        ModelDefaultUpdate: {
            /** Model Name */
            model_name?: string | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Fallback Chain */
            fallback_chain?: string[] | null;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Provider */
            provider: string;
            /** Provider Name */
            provider_name: string;
            /** Model Id */
            model_id: string;
            /** Mode */
            mode: string;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Input Cost Per Token */
            input_cost_per_token?: number | null;
            /** Output Cost Per Token */
            output_cost_per_token?: number | null;
            /**
             * Supports Vision
             * @default false
             */
            supports_vision: boolean;
            /**
             * Supports Function Calling
             * @default false
             */
            supports_function_calling: boolean;
        };
        /** NodeEvalResult */
        NodeEvalResult: {
            /** Node Id */
            node_id: string;
            /** Block Id */
            block_id: string;
            /** Soul Id */
            soul_id: string | null;
            /** Prompt Hash */
            prompt_hash: string | null;
            /** Soul Version */
            soul_version: string | null;
            /** Eval Score */
            eval_score: number | null;
            /** Passed */
            passed: boolean | null;
            /** Assertions */
            assertions: {
                [key: string]: unknown;
            }[] | null;
            delta: components["schemas"]["EvalDelta"] | null;
        };
        /** NodeSummary */
        NodeSummary: {
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Running */
            running: number;
            /** Pending */
            pending: number;
            /** Failed */
            failed: number;
        };
        /** PaginatedLogsResponse */
        PaginatedLogsResponse: {
            /** Items */
            items: components["schemas"]["runsight_api__transport__schemas__runs__LogResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Name */
            name: string;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ProviderSummary */
        ProviderSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Model Count */
            model_count: number;
            /**
             * Is Configured
             * @default false
             */
            is_configured: boolean;
        };
        /** ProviderTestIn */
        ProviderTestIn: {
            /** Provider Id */
            provider_id?: string | null;
            /** Provider Type */
            provider_type?: string | null;
            /** Name */
            name?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Name */
            name?: string | null;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** RunCreate */
        RunCreate: {
            /** Workflow Id */
            workflow_id: string;
            /** Task Data */
            task_data?: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @default manual
             */
            source: string | null;
            /**
             * Branch
             * @default main
             */
            branch: string;
        };
        /** RunEvalResponse */
        RunEvalResponse: {
            /** Run Id */
            run_id: string;
            /** Aggregate Score */
            aggregate_score: number | null;
            /** Passed */
            passed: boolean | null;
            /** Nodes */
            nodes: components["schemas"]["NodeEvalResult"][];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** RunNodeResponse */
        RunNodeResponse: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Node Id */
            node_id: string;
            /** Block Type */
            block_type: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: number | null;
            /** Completed At */
            completed_at: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Cost Usd */
            cost_usd: number;
            /** Tokens */
            tokens: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Workflow Name */
            workflow_name: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: number | null;
            /** Completed At */
            completed_at: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Tokens */
            total_tokens: number;
            /** Created At */
            created_at: number;
            /**
             * Branch
             * @default main
             */
            branch: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /** Run Number */
            run_number?: number | null;
            /** Eval Pass Pct */
            eval_pass_pct?: number | null;
            node_summary?: components["schemas"]["NodeSummary"] | null;
        };
        /** SettingsBudgetListResponse */
        SettingsBudgetListResponse: {
            /** Items */
            items: components["schemas"]["SettingsBudgetResponse"][];
            /** Total */
            total: number;
        };
        /** SettingsBudgetResponse */
        SettingsBudgetResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Limit Usd */
            limit_usd: number;
            /** Spent Usd */
            spent_usd: number;
            /** Period */
            period: string;
            /** Reset At */
            reset_at?: string | null;
        };
        /** SettingsModelDefaultListResponse */
        SettingsModelDefaultListResponse: {
            /** Items */
            items: components["schemas"]["SettingsModelDefaultResponse"][];
            /** Total */
            total: number;
        };
        /** SettingsModelDefaultResponse */
        SettingsModelDefaultResponse: {
            /** Id */
            id: string;
            /** Model Name */
            model_name: string;
            /** Provider Id */
            provider_id: string;
            /** Provider Name */
            provider_name: string;
            /**
             * Fallback Chain
             * @default []
             */
            fallback_chain: string[];
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** SettingsProviderListResponse */
        SettingsProviderListResponse: {
            /** Items */
            items: components["schemas"]["SettingsProviderResponse"][];
            /** Total */
            total: number;
        };
        /** SettingsProviderResponse */
        SettingsProviderResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /** Status */
            status: string;
            /** Api Key Env */
            api_key_env?: string | null;
            /** Api Key Preview */
            api_key_preview?: string | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Models
             * @default []
             */
            models: string[];
            /**
             * Model Count
             * @default 0
             */
            model_count: number;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SimBranchRequest */
        SimBranchRequest: {
            /** Workflow Id */
            workflow_id: string;
            /** Yaml Content */
            yaml_content: string;
        };
        /** SimBranchResponse */
        SimBranchResponse: {
            /** Branch */
            branch: string;
            /** Commit Sha */
            commit_sha: string;
        };
        /** SoulCreate */
        SoulCreate: {
            /** Id */
            id?: string | null;
            /** Role */
            role: string;
            /** System Prompt */
            system_prompt: string;
            /** Tools */
            tools?: string[] | null;
            /**
             * Max Tool Iterations
             * @default 5
             */
            max_tool_iterations: number;
            /** Model Name */
            model_name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Avatar Color */
            avatar_color?: string | null;
        };
        /** SoulEvalHistoryResponse */
        SoulEvalHistoryResponse: {
            /** Soul Id */
            soul_id: string;
            /** Versions */
            versions: components["schemas"]["SoulVersionEntry"][];
        };
        /** SoulListResponse */
        SoulListResponse: {
            /** Items */
            items: components["schemas"]["SoulResponse"][];
            /** Total */
            total: number;
        };
        /** SoulResponse */
        SoulResponse: {
            /** Id */
            id: string;
            /** Role */
            role?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Tools */
            tools?: string[] | null;
            /**
             * Max Tool Iterations
             * @default 5
             */
            max_tool_iterations: number;
            /** Model Name */
            model_name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Avatar Color */
            avatar_color?: string | null;
            /**
             * Workflow Count
             * @default 0
             */
            workflow_count: number;
        };
        /** SoulUpdate */
        SoulUpdate: {
            /** Role */
            role?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Tools */
            tools?: string[] | null;
            /** Max Tool Iterations */
            max_tool_iterations?: number | null;
            /** Model Name */
            model_name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Avatar Color */
            avatar_color?: string | null;
            /**
             * Copy On Edit
             * @default false
             */
            copy_on_edit: boolean;
        };
        /** SoulUsageEntry */
        SoulUsageEntry: {
            /** Workflow Id */
            workflow_id: string;
            /** Workflow Name */
            workflow_name: string;
        };
        /** SoulUsageResponse */
        SoulUsageResponse: {
            /** Soul Id */
            soul_id: string;
            /** Usages */
            usages: components["schemas"]["SoulUsageEntry"][];
            /** Total */
            total: number;
        };
        /** SoulVersionEntry */
        SoulVersionEntry: {
            /** Soul Version */
            soul_version: string;
            /** Avg Score */
            avg_score: number | null;
            /** Avg Cost */
            avg_cost: number;
            /** Run Count */
            run_count: number;
            /** First Seen */
            first_seen: number | string;
            /** Last Seen */
            last_seen: number | string;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Branch */
            branch: string;
            /** Uncommitted Files */
            uncommitted_files: components["schemas"]["UncommittedFile"][];
            /** Is Clean */
            is_clean: boolean;
        };
        /** StepCreate */
        StepCreate: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Type
             * @default step
             */
            type: string;
            /** Description */
            description?: string | null;
        };
        /** StepListResponse */
        StepListResponse: {
            /** Items */
            items: components["schemas"]["StepResponse"][];
            /** Total */
            total: number;
        };
        /** StepResponse */
        StepResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Path */
            path: string;
            /** Description */
            description?: string | null;
        };
        /** StepUpdate */
        StepUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Description */
            description?: string | null;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Type
             * @default task
             */
            type: string;
            /** Description */
            description?: string | null;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Items */
            items: components["schemas"]["TaskResponse"][];
            /** Total */
            total: number;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Path */
            path: string;
            /** Description */
            description?: string | null;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Description */
            description?: string | null;
        };
        /** UncommittedFile */
        UncommittedFile: {
            /** Path */
            path: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowCanvasState */
        WorkflowCanvasState: {
            /** Nodes */
            nodes?: {
                [key: string]: unknown;
            }[];
            /** Edges */
            edges?: {
                [key: string]: unknown;
            }[];
            viewport?: components["schemas"]["CanvasViewport"];
            /** Selected Node Id */
            selected_node_id?: string | null;
            /**
             * Canvas Mode
             * @default dag
             * @enum {string}
             */
            canvas_mode: "dag" | "state-machine";
        };
        /** WorkflowCommitCreate */
        WorkflowCommitCreate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Yaml */
            yaml?: string | null;
            canvas_state?: components["schemas"]["WorkflowCanvasState"] | null;
            /** Message */
            message: string;
        };
        /** WorkflowCommitResponse */
        WorkflowCommitResponse: {
            /** Hash */
            hash: string;
            /** Message */
            message: string;
        };
        /** WorkflowCreate */
        WorkflowCreate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Yaml */
            yaml?: string | null;
            canvas_state?: components["schemas"]["WorkflowCanvasState"] | null;
        };
        /** WorkflowDeleteResponse */
        WorkflowDeleteResponse: {
            /** Id */
            id: string;
            /** Deleted */
            deleted: boolean;
            /** Runs Deleted */
            runs_deleted: number;
        };
        /** WorkflowEnabledUpdate */
        WorkflowEnabledUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** WorkflowHealthMetrics */
        WorkflowHealthMetrics: {
            /**
             * Run Count
             * @default 0
             */
            run_count: number;
            /** Eval Pass Pct */
            eval_pass_pct?: number | null;
            /** Eval Health */
            eval_health?: ("success" | "warning" | "danger") | null;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /**
             * Regression Count
             * @default 0
             */
            regression_count: number;
        };
        /** WorkflowListResponse */
        WorkflowListResponse: {
            /** Items */
            items: components["schemas"]["WorkflowResponse"][];
            /** Total */
            total: number;
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Yaml */
            yaml?: string | null;
            canvas_state?: components["schemas"]["WorkflowCanvasState"] | null;
            /**
             * Valid
             * @default true
             */
            valid: boolean;
            /** Validation Error */
            validation_error?: string | null;
            /**
             * Block Count
             * @default 0
             */
            block_count: number;
            /** Modified At */
            modified_at?: number | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Commit Sha */
            commit_sha?: string | null;
            health?: components["schemas"]["WorkflowHealthMetrics"];
        };
        /** WorkflowSimulationCreate */
        WorkflowSimulationCreate: {
            /** Yaml */
            yaml: string;
        };
        /** WorkflowSimulationResponse */
        WorkflowSimulationResponse: {
            /** Branch */
            branch: string;
            /** Commit Sha */
            commit_sha: string;
        };
        /** WorkflowUpdate */
        WorkflowUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Yaml */
            yaml?: string | null;
            canvas_state?: components["schemas"]["WorkflowCanvasState"] | null;
        };
        /** LogResponse */
        runsight_api__transport__routers__git__LogResponse: {
            /** Commits */
            commits: components["schemas"]["CommitEntry"][];
        };
        /** LogResponse */
        runsight_api__transport__schemas__runs__LogResponse: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Timestamp */
            timestamp: number;
            /** Level */
            level: string;
            /** Node Id */
            node_id: string | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_run_eval_api_runs__run_id__eval_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_soul_eval_history_api_souls__soul_id__eval_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                soul_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulEvalHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                workflow_id?: string | null;
                source?: string[] | null;
                branch?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_logs_api_runs__run_id__logs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_nodes_api_runs__run_id__nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunNodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_api_workflows_get: {
        parameters: {
            query?: {
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_api_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_workflows__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_api_workflows__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_api_workflows__id__delete: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_workflow_enabled_api_workflows__id__enabled_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowEnabledUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_workflow_api_workflows__id__commits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCommitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowCommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workflow_simulation_api_workflows__id__simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowSimulationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_souls_api_souls_get: {
        parameters: {
            query?: {
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_soul_api_souls_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoulCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_soul_usages_api_souls__id__usages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulUsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_soul_api_souls__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_soul_api_souls__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoulUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoulResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_soul_api_souls__id__delete: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_steps_api_steps_get: {
        parameters: {
            query?: {
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_step_api_steps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_step_api_steps__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_step_api_steps__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_step_api_steps__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_tasks__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_settings_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProviderListResponse"];
                };
            };
        };
    };
    create_provider_api_settings_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_api_settings_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider_api_settings_providers__provider_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider_api_settings_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider_api_settings_providers__provider_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider_credentials_api_settings_providers_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderTestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_model_defaults_api_settings_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModelDefaultListResponse"];
                };
            };
        };
    };
    update_model_default_api_settings_models__model_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelDefaultUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModelDefaultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_budgets_api_settings_budgets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBudgetListResponse"];
                };
            };
        };
    };
    get_app_settings_api_settings_app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
        };
    };
    update_app_settings_api_settings_app_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsOut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKPIsResponse"];
                };
            };
        };
    };
    get_attention_items_api_dashboard_attention_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionItemsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_status_api_git_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    git_commit_api_git_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_diff_api_git_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
        };
    };
    git_log_api_git_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runsight_api__transport__routers__git__LogResponse"];
                };
            };
        };
    };
    create_sim_branch_api_git_sim_branch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimBranchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimBranchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: {
                provider?: string | null;
                mode?: string | null;
                supports_vision?: boolean | null;
                supports_function_calling?: boolean | null;
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_models_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSummary"][];
                };
            };
        };
    };
    stream_run_events_api_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}

export const components = {};
