// Auto-generated by tools/generate-zod-schemas.py — DO NOT EDIT
// Source: openapi.json (RUN-134)

import { z } from "zod";

export const AppSettingsOutSchema = z.object({
  base_path: z.string().nullable().optional(),
  onboarding_completed: z.boolean().optional(),
  fallback_enabled: z.boolean().optional(),
});
export type AppSettingsOut = z.infer<typeof AppSettingsOutSchema>;

export const AppSettingsUpdateSchema = z.object({
  onboarding_completed: z.boolean().optional(),
  fallback_enabled: z.boolean().optional(),
}).strict();
export type AppSettingsUpdate = z.infer<typeof AppSettingsUpdateSchema>;

export const AttentionItemSchema = z.object({
  type: z.enum(["assertion_regression", "cost_spike", "quality_drop", "new_baseline"]),
  title: z.string(),
  description: z.string(),
  run_id: z.string(),
  workflow_id: z.string(),
  severity: z.enum(["warning", "info"]),
});
export type AttentionItem = z.infer<typeof AttentionItemSchema>;

export const AttentionItemsResponseSchema = z.object({
  items: z.array(AttentionItemSchema),
});
export type AttentionItemsResponse = z.infer<typeof AttentionItemsResponseSchema>;

export const CanvasViewportSchema = z.object({
  x: z.number().optional().default(0.0),
  y: z.number().optional().default(0.0),
  zoom: z.number().optional().default(1.0),
});
export type CanvasViewport = z.infer<typeof CanvasViewportSchema>;

export const CommitEntrySchema = z.object({
  hash: z.string(),
  message: z.string(),
  date: z.string(),
  author: z.string(),
});
export type CommitEntry = z.infer<typeof CommitEntrySchema>;

export const CommitRequestSchema = z.object({
  message: z.string(),
  files: z.array(z.string()).nullable().optional(),
});
export type CommitRequest = z.infer<typeof CommitRequestSchema>;

export const CommitResponseSchema = z.object({
  hash: z.string(),
  message: z.string(),
});
export type CommitResponse = z.infer<typeof CommitResponseSchema>;

export const ContextAccessSchema = z.enum(["declared", "all"]);
export type ContextAccess = z.infer<typeof ContextAccessSchema>;

export const ContextAuditModeSchema = z.enum(["strict", "dev"]);
export type ContextAuditMode = z.infer<typeof ContextAuditModeSchema>;

export const ContextAuditStatusSchema = z.enum(["resolved", "missing", "denied", "all_access", "empty"]);
export type ContextAuditStatus = z.infer<typeof ContextAuditStatusSchema>;

export const ContextAuditNamespaceSchema = z.enum(["results", "shared_memory", "metadata"]);
export type ContextAuditNamespace = z.infer<typeof ContextAuditNamespaceSchema>;

export const ContextAuditSeveritySchema = z.enum(["allow", "warn", "error"]);
export type ContextAuditSeverity = z.infer<typeof ContextAuditSeveritySchema>;

export const ContextAuditRecordV1Schema = z.object({
  input_name: z.string().nullable(),
  from_ref: z.string().nullable(),
  namespace: ContextAuditNamespaceSchema.nullable(),
  source: z.string().nullable(),
  field_path: z.string().nullable().optional(),
  status: ContextAuditStatusSchema,
  severity: ContextAuditSeveritySchema,
  value_type: z.string().nullable().optional(),
  preview: z.string().nullable().optional(),
  reason: z.string().nullable().optional(),
  internal: z.boolean().optional().default(false),
}).strict();
export type ContextAuditRecordV1 = z.infer<typeof ContextAuditRecordV1Schema>;

export const ContextAuditEventV1Schema = z.object({
  schema_version: z.literal("context_audit.v1").optional().default("context_audit.v1"),
  event: z.literal("context_resolution").optional().default("context_resolution"),
  run_id: z.string(),
  workflow_name: z.string(),
  node_id: z.string(),
  block_type: z.string(),
  access: ContextAccessSchema,
  mode: ContextAuditModeSchema,
  sequence: z.number().nullable().optional(),
  records: z.array(ContextAuditRecordV1Schema).optional(),
  resolved_count: z.number().optional().default(0),
  denied_count: z.number().optional().default(0),
  warning_count: z.number().optional().default(0),
  emitted_at: z.string(),
}).strict();
export type ContextAuditEventV1 = z.infer<typeof ContextAuditEventV1Schema>;

export const ContextAuditListResponseSchema = z.object({
  items: z.array(ContextAuditEventV1Schema),
  page_size: z.number(),
  has_next_page: z.boolean(),
  end_cursor: z.string().nullable().optional(),
});
export type ContextAuditListResponse = z.infer<typeof ContextAuditListResponseSchema>;

export const DashboardKPIsResponseSchema = z.object({
  runs_today: z.number(),
  cost_today_usd: z.number(),
  eval_pass_rate: z.number().nullable(),
  regressions: z.number().nullable(),
  runs_previous_period: z.number().optional().default(0),
  cost_previous_period_usd: z.number().optional().default(0.0),
  eval_pass_rate_previous_period: z.number().nullable().optional(),
  regressions_previous_period: z.number().nullable().optional(),
  period_hours: z.number().optional().default(24),
});
export type DashboardKPIsResponse = z.infer<typeof DashboardKPIsResponseSchema>;

export const DiffResponseSchema = z.object({
  diff: z.string(),
});
export type DiffResponse = z.infer<typeof DiffResponseSchema>;

export const EvalDeltaSchema = z.object({
  cost_pct: z.number(),
  tokens_pct: z.number(),
  score_delta: z.number().nullable(),
  baseline_run_count: z.number(),
});
export type EvalDelta = z.infer<typeof EvalDeltaSchema>;

export const FallbackUpdateSchema = z.object({
  fallback_provider_id: z.string().nullable().optional(),
  fallback_model_id: z.string().nullable().optional(),
});
export type FallbackUpdate = z.infer<typeof FallbackUpdateSchema>;

export const FileReadResponseSchema = z.object({
  content: z.string(),
  ref: z.string(),
});
export type FileReadResponse = z.infer<typeof FileReadResponseSchema>;

export const ValidationErrorSchema = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
  input: z.string().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});
export type ValidationError = z.infer<typeof ValidationErrorSchema>;

export const HTTPValidationErrorSchema = z.object({
  detail: z.array(ValidationErrorSchema).optional(),
});
export type HTTPValidationError = z.infer<typeof HTTPValidationErrorSchema>;

export const ModelResponseSchema = z.object({
  provider: z.string(),
  provider_name: z.string(),
  model_id: z.string(),
  mode: z.string(),
  max_tokens: z.number().nullable().optional(),
  input_cost_per_token: z.number().nullable().optional(),
  output_cost_per_token: z.number().nullable().optional(),
  supports_vision: z.boolean().optional().default(false),
  supports_function_calling: z.boolean().optional().default(false),
});
export type ModelResponse = z.infer<typeof ModelResponseSchema>;

export const ModelListResponseSchema = z.object({
  items: z.array(ModelResponseSchema),
  total: z.number(),
});
export type ModelListResponse = z.infer<typeof ModelListResponseSchema>;

export const NodeEvalResultSchema = z.object({
  node_id: z.string(),
  block_id: z.string(),
  soul_id: z.string().nullable(),
  prompt_hash: z.string().nullable(),
  soul_version: z.string().nullable(),
  eval_score: z.number().nullable(),
  passed: z.boolean().nullable(),
  assertions: z.array(z.record(z.string(), z.unknown())).nullable(),
  delta: EvalDeltaSchema.nullable(),
});
export type NodeEvalResult = z.infer<typeof NodeEvalResultSchema>;

export const NodeSummarySchema = z.object({
  total: z.number(),
  completed: z.number(),
  running: z.number(),
  pending: z.number(),
  failed: z.number(),
});
export type NodeSummary = z.infer<typeof NodeSummarySchema>;

export const runsight_api__transport__schemas__runs__LogResponseSchema = z.object({
  id: z.number(),
  run_id: z.string(),
  timestamp: z.number(),
  level: z.string(),
  node_id: z.string().nullable(),
  message: z.string(),
});
export type runsight_api__transport__schemas__runs__LogResponse = z.infer<typeof runsight_api__transport__schemas__runs__LogResponseSchema>;

export const PaginatedLogsResponseSchema = z.object({
  items: z.array(runsight_api__transport__schemas__runs__LogResponseSchema),
  total: z.number(),
  offset: z.number(),
  limit: z.number(),
});
export type PaginatedLogsResponse = z.infer<typeof PaginatedLogsResponseSchema>;

export const ProviderCreateSchema = z.object({
  id: z.string(),
  kind: z.literal("provider"),
  name: z.string(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
}).strict();
export type ProviderCreate = z.infer<typeof ProviderCreateSchema>;

export const ProviderSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  model_count: z.number(),
  is_configured: z.boolean().optional().default(false),
});
export type ProviderSummary = z.infer<typeof ProviderSummarySchema>;

export const ProviderTestInSchema = z.object({
  provider_id: z.string().nullable().optional(),
  provider_type: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
});
export type ProviderTestIn = z.infer<typeof ProviderTestInSchema>;

export const ProviderTestOutSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  models: z.array(z.string()).optional(),
  model_count: z.number().optional().default(0),
  latency_ms: z.number().optional().default(0.0),
});
export type ProviderTestOut = z.infer<typeof ProviderTestOutSchema>;

export const ProviderUpdateSchema = z.object({
  id: z.string(),
  kind: z.literal("provider"),
  name: z.string().nullable().optional(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
  is_active: z.boolean().nullable().optional(),
}).strict();
export type ProviderUpdate = z.infer<typeof ProviderUpdateSchema>;

export const RunCreateSchema = z.object({
  workflow_id: z.string(),
  inputs: z.record(z.string(), z.unknown()).optional(),
  source: z.string().nullable().optional().default("manual"),
  branch: z.string().optional().default("main"),
}).strict();
export type RunCreate = z.infer<typeof RunCreateSchema>;

export const RunEvalResponseSchema = z.object({
  run_id: z.string(),
  aggregate_score: z.number().nullable(),
  passed: z.boolean().nullable(),
  nodes: z.array(NodeEvalResultSchema),
});
export type RunEvalResponse = z.infer<typeof RunEvalResponseSchema>;

export const WarningItemSchema = z.object({
  message: z.string(),
  source: z.string().nullable().optional(),
  context: z.string().nullable().optional(),
}).strict();
export type WarningItem = z.infer<typeof WarningItemSchema>;

export const RunResponseSchema = z.object({
  id: z.string(),
  workflow_id: z.string(),
  workflow_name: z.string(),
  status: z.string(),
  error: z.string().nullable().optional(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  duration_seconds: z.number().nullable(),
  total_cost_usd: z.number(),
  total_tokens: z.number(),
  created_at: z.number(),
  branch: z.string().optional().default("main"),
  source: z.string().optional().default("manual"),
  commit_sha: z.string().nullable().optional(),
  run_number: z.number().nullable().optional(),
  eval_pass_pct: z.number().nullable().optional(),
  eval_score_avg: z.number().nullable().optional(),
  regression_count: z.number().nullable().optional().default(0),
  regression_types: z.array(z.string()).optional(),
  warnings: z.array(WarningItemSchema).optional(),
  node_summary: NodeSummarySchema.nullable().optional(),
  parent_run_id: z.string().nullable().optional(),
  root_run_id: z.string().nullable().optional(),
  depth: z.number().optional().default(0),
});
export type RunResponse = z.infer<typeof RunResponseSchema>;

export const RunListResponseSchema = z.object({
  items: z.array(RunResponseSchema),
  total: z.number(),
  offset: z.number(),
  limit: z.number(),
});
export type RunListResponse = z.infer<typeof RunListResponseSchema>;

export const RunNodeResponseSchema = z.object({
  id: z.string(),
  run_id: z.string(),
  node_id: z.string(),
  block_type: z.string(),
  status: z.string(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  duration_seconds: z.number().nullable(),
  cost_usd: z.number(),
  tokens: z.record(z.string(), z.unknown()),
  error: z.string().nullable(),
  output: z.string().nullable().optional(),
  soul_id: z.string().nullable().optional(),
  model_name: z.string().nullable().optional(),
  eval_score: z.number().nullable().optional(),
  eval_passed: z.boolean().nullable().optional(),
  eval_results: z.record(z.string(), z.unknown()).nullable().optional(),
  child_run_id: z.string().nullable().optional(),
  exit_handle: z.string().nullable().optional(),
});
export type RunNodeResponse = z.infer<typeof RunNodeResponseSchema>;

export const SettingsFallbackResponseSchema = z.object({
  id: z.string(),
  provider_id: z.string(),
  provider_name: z.string(),
  fallback_provider_id: z.string().nullable().optional(),
  fallback_model_id: z.string().nullable().optional(),
});
export type SettingsFallbackResponse = z.infer<typeof SettingsFallbackResponseSchema>;

export const SettingsFallbackListResponseSchema = z.object({
  items: z.array(SettingsFallbackResponseSchema),
  total: z.number(),
});
export type SettingsFallbackListResponse = z.infer<typeof SettingsFallbackListResponseSchema>;

export const SettingsProviderResponseSchema = z.object({
  id: z.string(),
  kind: z.literal("provider"),
  name: z.string(),
  type: z.string().nullable().optional(),
  status: z.string(),
  is_active: z.boolean().optional().default(true),
  api_key_env: z.string().nullable().optional(),
  api_key_preview: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
  models: z.array(z.string()).optional(),
  model_count: z.number().optional().default(0),
  created_at: z.string().nullable().optional(),
  updated_at: z.string().nullable().optional(),
});
export type SettingsProviderResponse = z.infer<typeof SettingsProviderResponseSchema>;

export const SettingsProviderListResponseSchema = z.object({
  items: z.array(SettingsProviderResponseSchema),
  total: z.number(),
});
export type SettingsProviderListResponse = z.infer<typeof SettingsProviderListResponseSchema>;

export const SimBranchRequestSchema = z.object({
  workflow_id: z.string(),
  yaml_content: z.string(),
});
export type SimBranchRequest = z.infer<typeof SimBranchRequestSchema>;

export const SimBranchResponseSchema = z.object({
  branch: z.string(),
  commit_sha: z.string(),
});
export type SimBranchResponse = z.infer<typeof SimBranchResponseSchema>;

export const SoulCreateSchema = z.object({
  id: z.string(),
  kind: z.literal("soul"),
  name: z.string(),
  role: z.string(),
  system_prompt: z.string(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().optional().default(5),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
}).strict();
export type SoulCreate = z.infer<typeof SoulCreateSchema>;

export const SoulVersionEntrySchema = z.object({
  soul_version: z.string(),
  avg_score: z.number().nullable(),
  avg_cost: z.number(),
  run_count: z.number(),
  first_seen: z.union([z.number(), z.string()]),
  last_seen: z.union([z.number(), z.string()]),
});
export type SoulVersionEntry = z.infer<typeof SoulVersionEntrySchema>;

export const SoulEvalHistoryResponseSchema = z.object({
  soul_id: z.string(),
  versions: z.array(SoulVersionEntrySchema),
});
export type SoulEvalHistoryResponse = z.infer<typeof SoulEvalHistoryResponseSchema>;

export const SoulResponseSchema = z.object({
  kind: z.literal("soul"),
  name: z.string(),
  id: z.string(),
  role: z.string().nullable().optional(),
  system_prompt: z.string().nullable().optional(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().optional().default(5),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
  workflow_count: z.number().optional().default(0),
  modified_at: z.number().nullable().optional(),
});
export type SoulResponse = z.infer<typeof SoulResponseSchema>;

export const SoulListResponseSchema = z.object({
  items: z.array(SoulResponseSchema),
  total: z.number(),
});
export type SoulListResponse = z.infer<typeof SoulListResponseSchema>;

export const SoulUpdateSchema = z.object({
  role: z.string().nullable().optional(),
  system_prompt: z.string().nullable().optional(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().nullable().optional(),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
  copy_on_edit: z.boolean().optional().default(false),
}).strict();
export type SoulUpdate = z.infer<typeof SoulUpdateSchema>;

export const SoulUsageEntrySchema = z.object({
  workflow_id: z.string(),
  workflow_name: z.string(),
});
export type SoulUsageEntry = z.infer<typeof SoulUsageEntrySchema>;

export const SoulUsageResponseSchema = z.object({
  soul_id: z.string(),
  usages: z.array(SoulUsageEntrySchema),
  total: z.number(),
});
export type SoulUsageResponse = z.infer<typeof SoulUsageResponseSchema>;

export const UncommittedFileSchema = z.object({
  path: z.string(),
  status: z.string(),
});
export type UncommittedFile = z.infer<typeof UncommittedFileSchema>;

export const StatusResponseSchema = z.object({
  branch: z.string(),
  uncommitted_files: z.array(UncommittedFileSchema),
  is_clean: z.boolean(),
});
export type StatusResponse = z.infer<typeof StatusResponseSchema>;

export const ToolListItemResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  origin: z.enum(["builtin", "custom"]),
  executor: z.enum(["native", "python", "request"]),
});
export type ToolListItemResponse = z.infer<typeof ToolListItemResponseSchema>;

export const WorkflowCanvasStateSchema = z.object({
  nodes: z.array(z.record(z.string(), z.unknown())).optional(),
  edges: z.array(z.record(z.string(), z.unknown())).optional(),
  viewport: CanvasViewportSchema.optional(),
  selected_node_id: z.string().nullable().optional(),
  canvas_mode: z.enum(["dag", "state-machine"]).optional().default("dag"),
});
export type WorkflowCanvasState = z.infer<typeof WorkflowCanvasStateSchema>;

export const WorkflowCommitCreateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
  message: z.string(),
});
export type WorkflowCommitCreate = z.infer<typeof WorkflowCommitCreateSchema>;

export const WorkflowCommitResponseSchema = z.object({
  hash: z.string(),
  message: z.string(),
});
export type WorkflowCommitResponse = z.infer<typeof WorkflowCommitResponseSchema>;

export const WorkflowCreateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
  commit: z.boolean().optional().default(true),
});
export type WorkflowCreate = z.infer<typeof WorkflowCreateSchema>;

export const WorkflowDeleteResponseSchema = z.object({
  id: z.string(),
  deleted: z.boolean(),
  runs_deleted: z.number(),
});
export type WorkflowDeleteResponse = z.infer<typeof WorkflowDeleteResponseSchema>;

export const WorkflowEnabledUpdateSchema = z.object({
  enabled: z.boolean(),
});
export type WorkflowEnabledUpdate = z.infer<typeof WorkflowEnabledUpdateSchema>;

export const WorkflowHealthMetricsSchema = z.object({
  run_count: z.number().optional().default(0),
  eval_pass_pct: z.number().nullable().optional(),
  eval_health: z.enum(["success", "warning", "danger"]).nullable().optional(),
  total_cost_usd: z.number().optional().default(0.0),
  regression_count: z.number().optional().default(0),
});
export type WorkflowHealthMetrics = z.infer<typeof WorkflowHealthMetricsSchema>;

export const WorkflowResponseSchema = z.object({
  kind: z.literal("workflow"),
  id: z.string(),
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string().nullable().optional(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
  valid: z.boolean().optional().default(true),
  validation_error: z.string().nullable().optional(),
  warnings: z.array(WarningItemSchema).optional(),
  block_count: z.number().optional().default(0),
  modified_at: z.number().nullable().optional(),
  enabled: z.boolean().optional().default(false),
  commit_sha: z.string().nullable().optional(),
  health: WorkflowHealthMetricsSchema.optional(),
});
export type WorkflowResponse = z.infer<typeof WorkflowResponseSchema>;

export const WorkflowListResponseSchema = z.object({
  items: z.array(WorkflowResponseSchema),
  total: z.number(),
});
export type WorkflowListResponse = z.infer<typeof WorkflowListResponseSchema>;

export const WorkflowSimulationCreateSchema = z.object({
  yaml: z.string(),
});
export type WorkflowSimulationCreate = z.infer<typeof WorkflowSimulationCreateSchema>;

export const WorkflowSimulationResponseSchema = z.object({
  branch: z.string(),
  commit_sha: z.string(),
});
export type WorkflowSimulationResponse = z.infer<typeof WorkflowSimulationResponseSchema>;

export const WorkflowUpdateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
});
export type WorkflowUpdate = z.infer<typeof WorkflowUpdateSchema>;

export const runsight_api__transport__schemas__git__LogResponseSchema = z.object({
  commits: z.array(CommitEntrySchema),
});
export type runsight_api__transport__schemas__git__LogResponse = z.infer<typeof runsight_api__transport__schemas__git__LogResponseSchema>;
