// Auto-generated by tools/generate-zod-schemas.py — DO NOT EDIT
// Source: openapi.json (RUN-134)

import { z } from "zod";

export const AppSettingsOutSchema = z.object({
  base_path: z.string().nullable().optional(),
  default_provider: z.string().nullable().optional(),
  auto_save: z.boolean().nullable().optional(),
  onboarding_completed: z.boolean().nullable().optional(),
  fallback_chain_enabled: z.boolean().nullable().optional(),
});
export type AppSettingsOut = z.infer<typeof AppSettingsOutSchema>;

export const AttentionItemSchema = z.object({
  type: z.string(),
  title: z.string(),
  description: z.string(),
  run_id: z.string(),
  workflow_id: z.string(),
  severity: z.string(),
});
export type AttentionItem = z.infer<typeof AttentionItemSchema>;

export const AttentionItemsResponseSchema = z.object({
  items: z.array(AttentionItemSchema),
});
export type AttentionItemsResponse = z.infer<typeof AttentionItemsResponseSchema>;

export const CanvasViewportSchema = z.object({
  x: z.number().optional().default(0.0),
  y: z.number().optional().default(0.0),
  zoom: z.number().optional().default(1.0),
});
export type CanvasViewport = z.infer<typeof CanvasViewportSchema>;

export const CommitEntrySchema = z.object({
  hash: z.string(),
  message: z.string(),
  date: z.string(),
  author: z.string(),
});
export type CommitEntry = z.infer<typeof CommitEntrySchema>;

export const CommitRequestSchema = z.object({
  message: z.string(),
  files: z.array(z.string()).nullable().optional(),
});
export type CommitRequest = z.infer<typeof CommitRequestSchema>;

export const CommitResponseSchema = z.object({
  hash: z.string(),
  message: z.string(),
});
export type CommitResponse = z.infer<typeof CommitResponseSchema>;

export const DashboardKPIsResponseSchema = z.object({
  runs_today: z.number(),
  cost_today_usd: z.number(),
  eval_pass_rate: z.number().nullable(),
  regressions: z.number().nullable(),
  runs_previous_period: z.number().optional().default(0),
  cost_previous_period_usd: z.number().optional().default(0.0),
  eval_pass_rate_previous_period: z.number().nullable().optional(),
  regressions_previous_period: z.number().nullable().optional(),
  period_hours: z.number().optional().default(24),
});
export type DashboardKPIsResponse = z.infer<typeof DashboardKPIsResponseSchema>;

export const DiffResponseSchema = z.object({
  diff: z.string(),
});
export type DiffResponse = z.infer<typeof DiffResponseSchema>;

export const EvalDeltaSchema = z.object({
  cost_pct: z.number(),
  tokens_pct: z.number(),
  score_delta: z.number().nullable(),
  baseline_run_count: z.number(),
});
export type EvalDelta = z.infer<typeof EvalDeltaSchema>;

export const ValidationErrorSchema = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
  input: z.string().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});
export type ValidationError = z.infer<typeof ValidationErrorSchema>;

export const HTTPValidationErrorSchema = z.object({
  detail: z.array(ValidationErrorSchema).optional(),
});
export type HTTPValidationError = z.infer<typeof HTTPValidationErrorSchema>;

export const ModelDefaultUpdateSchema = z.object({
  model_name: z.string().nullable().optional(),
  is_default: z.boolean().nullable().optional(),
  fallback_chain: z.array(z.string()).nullable().optional(),
});
export type ModelDefaultUpdate = z.infer<typeof ModelDefaultUpdateSchema>;

export const ModelResponseSchema = z.object({
  provider: z.string(),
  provider_name: z.string(),
  model_id: z.string(),
  mode: z.string(),
  max_tokens: z.number().nullable().optional(),
  input_cost_per_token: z.number().nullable().optional(),
  output_cost_per_token: z.number().nullable().optional(),
  supports_vision: z.boolean().optional().default(false),
  supports_function_calling: z.boolean().optional().default(false),
});
export type ModelResponse = z.infer<typeof ModelResponseSchema>;

export const NodeEvalResultSchema = z.object({
  node_id: z.string(),
  block_id: z.string(),
  soul_id: z.string().nullable(),
  prompt_hash: z.string().nullable(),
  soul_version: z.string().nullable(),
  eval_score: z.number().nullable(),
  passed: z.boolean().nullable(),
  assertions: z.array(z.record(z.string(), z.unknown())).nullable(),
  delta: EvalDeltaSchema.nullable(),
});
export type NodeEvalResult = z.infer<typeof NodeEvalResultSchema>;

export const NodeSummarySchema = z.object({
  total: z.number(),
  completed: z.number(),
  running: z.number(),
  pending: z.number(),
  failed: z.number(),
});
export type NodeSummary = z.infer<typeof NodeSummarySchema>;

export const runsight_api__transport__schemas__runs__LogResponseSchema = z.object({
  id: z.number(),
  run_id: z.string(),
  timestamp: z.number(),
  level: z.string(),
  node_id: z.string().nullable(),
  message: z.string(),
});
export type runsight_api__transport__schemas__runs__LogResponse = z.infer<typeof runsight_api__transport__schemas__runs__LogResponseSchema>;

export const PaginatedLogsResponseSchema = z.object({
  items: z.array(runsight_api__transport__schemas__runs__LogResponseSchema),
  total: z.number(),
  offset: z.number(),
  limit: z.number(),
});
export type PaginatedLogsResponse = z.infer<typeof PaginatedLogsResponseSchema>;

export const ProviderCreateSchema = z.object({
  name: z.string(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
});
export type ProviderCreate = z.infer<typeof ProviderCreateSchema>;

export const ProviderSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  model_count: z.number(),
  is_configured: z.boolean().optional().default(false),
});
export type ProviderSummary = z.infer<typeof ProviderSummarySchema>;

export const ProviderTestInSchema = z.object({
  provider_id: z.string().nullable().optional(),
  provider_type: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
});
export type ProviderTestIn = z.infer<typeof ProviderTestInSchema>;

export const ProviderTestOutSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  models: z.array(z.string()).optional(),
  model_count: z.number().optional().default(0),
  latency_ms: z.number().optional().default(0.0),
});
export type ProviderTestOut = z.infer<typeof ProviderTestOutSchema>;

export const ProviderUpdateSchema = z.object({
  name: z.string().nullable().optional(),
  api_key_env: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
});
export type ProviderUpdate = z.infer<typeof ProviderUpdateSchema>;

export const RunCreateSchema = z.object({
  workflow_id: z.string(),
  task_data: z.record(z.string(), z.unknown()).optional(),
  source: z.string().nullable().optional().default("manual"),
  branch: z.string().optional().default("main"),
});
export type RunCreate = z.infer<typeof RunCreateSchema>;

export const RunEvalResponseSchema = z.object({
  run_id: z.string(),
  aggregate_score: z.number().nullable(),
  passed: z.boolean().nullable(),
  nodes: z.array(NodeEvalResultSchema),
});
export type RunEvalResponse = z.infer<typeof RunEvalResponseSchema>;

export const RunResponseSchema = z.object({
  id: z.string(),
  workflow_id: z.string(),
  workflow_name: z.string(),
  status: z.string(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  duration_seconds: z.number().nullable(),
  total_cost_usd: z.number(),
  total_tokens: z.number(),
  created_at: z.number(),
  branch: z.string().optional().default("main"),
  source: z.string().optional().default("manual"),
  commit_sha: z.string().nullable().optional(),
  run_number: z.number().nullable().optional(),
  eval_pass_pct: z.number().nullable().optional(),
  node_summary: NodeSummarySchema.nullable().optional(),
});
export type RunResponse = z.infer<typeof RunResponseSchema>;

export const RunListResponseSchema = z.object({
  items: z.array(RunResponseSchema),
  total: z.number(),
  offset: z.number(),
  limit: z.number(),
});
export type RunListResponse = z.infer<typeof RunListResponseSchema>;

export const RunNodeResponseSchema = z.object({
  id: z.string(),
  run_id: z.string(),
  node_id: z.string(),
  block_type: z.string(),
  status: z.string(),
  started_at: z.number().nullable(),
  completed_at: z.number().nullable(),
  duration_seconds: z.number().nullable(),
  cost_usd: z.number(),
  tokens: z.record(z.string(), z.unknown()),
  error: z.string().nullable(),
});
export type RunNodeResponse = z.infer<typeof RunNodeResponseSchema>;

export const SettingsBudgetResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  limit_usd: z.number(),
  spent_usd: z.number(),
  period: z.string(),
  reset_at: z.string().nullable().optional(),
});
export type SettingsBudgetResponse = z.infer<typeof SettingsBudgetResponseSchema>;

export const SettingsBudgetListResponseSchema = z.object({
  items: z.array(SettingsBudgetResponseSchema),
  total: z.number(),
});
export type SettingsBudgetListResponse = z.infer<typeof SettingsBudgetListResponseSchema>;

export const SettingsModelDefaultResponseSchema = z.object({
  id: z.string(),
  model_name: z.string(),
  provider_id: z.string(),
  provider_name: z.string(),
  fallback_chain: z.array(z.string()).optional(),
  is_default: z.boolean().optional().default(false),
});
export type SettingsModelDefaultResponse = z.infer<typeof SettingsModelDefaultResponseSchema>;

export const SettingsModelDefaultListResponseSchema = z.object({
  items: z.array(SettingsModelDefaultResponseSchema),
  total: z.number(),
});
export type SettingsModelDefaultListResponse = z.infer<typeof SettingsModelDefaultListResponseSchema>;

export const SettingsProviderResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string().nullable().optional(),
  status: z.string(),
  api_key_env: z.string().nullable().optional(),
  api_key_preview: z.string().nullable().optional(),
  base_url: z.string().nullable().optional(),
  models: z.array(z.string()).optional(),
  model_count: z.number().optional().default(0),
  created_at: z.string().nullable().optional(),
  updated_at: z.string().nullable().optional(),
});
export type SettingsProviderResponse = z.infer<typeof SettingsProviderResponseSchema>;

export const SettingsProviderListResponseSchema = z.object({
  items: z.array(SettingsProviderResponseSchema),
  total: z.number(),
});
export type SettingsProviderListResponse = z.infer<typeof SettingsProviderListResponseSchema>;

export const SimBranchRequestSchema = z.object({
  workflow_id: z.string(),
  yaml_content: z.string(),
});
export type SimBranchRequest = z.infer<typeof SimBranchRequestSchema>;

export const SimBranchResponseSchema = z.object({
  branch: z.string(),
  commit_sha: z.string(),
});
export type SimBranchResponse = z.infer<typeof SimBranchResponseSchema>;

export const SoulCreateSchema = z.object({
  id: z.string().nullable().optional(),
  role: z.string(),
  system_prompt: z.string(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().optional().default(5),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
});
export type SoulCreate = z.infer<typeof SoulCreateSchema>;

export const SoulVersionEntrySchema = z.object({
  soul_version: z.string(),
  avg_score: z.number().nullable(),
  avg_cost: z.number(),
  run_count: z.number(),
  first_seen: z.union([z.number(), z.string()]),
  last_seen: z.union([z.number(), z.string()]),
});
export type SoulVersionEntry = z.infer<typeof SoulVersionEntrySchema>;

export const SoulEvalHistoryResponseSchema = z.object({
  soul_id: z.string(),
  versions: z.array(SoulVersionEntrySchema),
});
export type SoulEvalHistoryResponse = z.infer<typeof SoulEvalHistoryResponseSchema>;

export const SoulResponseSchema = z.object({
  id: z.string(),
  role: z.string().nullable().optional(),
  system_prompt: z.string().nullable().optional(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().optional().default(5),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
  workflow_count: z.number().optional().default(0),
});
export type SoulResponse = z.infer<typeof SoulResponseSchema>;

export const SoulListResponseSchema = z.object({
  items: z.array(SoulResponseSchema),
  total: z.number(),
});
export type SoulListResponse = z.infer<typeof SoulListResponseSchema>;

export const SoulUpdateSchema = z.object({
  role: z.string().nullable().optional(),
  system_prompt: z.string().nullable().optional(),
  tools: z.array(z.string()).nullable().optional(),
  max_tool_iterations: z.number().nullable().optional(),
  model_name: z.string().nullable().optional(),
  provider: z.string().nullable().optional(),
  temperature: z.number().nullable().optional(),
  max_tokens: z.number().nullable().optional(),
  avatar_color: z.string().nullable().optional(),
  copy_on_edit: z.boolean().optional().default(false),
});
export type SoulUpdate = z.infer<typeof SoulUpdateSchema>;

export const SoulUsageEntrySchema = z.object({
  workflow_id: z.string(),
  workflow_name: z.string(),
});
export type SoulUsageEntry = z.infer<typeof SoulUsageEntrySchema>;

export const SoulUsageResponseSchema = z.object({
  soul_id: z.string(),
  usages: z.array(SoulUsageEntrySchema),
  total: z.number(),
});
export type SoulUsageResponse = z.infer<typeof SoulUsageResponseSchema>;

export const UncommittedFileSchema = z.object({
  path: z.string(),
  status: z.string(),
});
export type UncommittedFile = z.infer<typeof UncommittedFileSchema>;

export const StatusResponseSchema = z.object({
  branch: z.string(),
  uncommitted_files: z.array(UncommittedFileSchema),
  is_clean: z.boolean(),
});
export type StatusResponse = z.infer<typeof StatusResponseSchema>;

export const StepCreateSchema = z.object({
  id: z.string().nullable().optional(),
  name: z.string(),
  type: z.string().optional().default("step"),
  description: z.string().nullable().optional(),
});
export type StepCreate = z.infer<typeof StepCreateSchema>;

export const StepResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  path: z.string(),
  description: z.string().nullable().optional(),
});
export type StepResponse = z.infer<typeof StepResponseSchema>;

export const StepListResponseSchema = z.object({
  items: z.array(StepResponseSchema),
  total: z.number(),
});
export type StepListResponse = z.infer<typeof StepListResponseSchema>;

export const StepUpdateSchema = z.object({
  name: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
});
export type StepUpdate = z.infer<typeof StepUpdateSchema>;

export const TaskCreateSchema = z.object({
  id: z.string().nullable().optional(),
  name: z.string(),
  type: z.string().optional().default("task"),
  description: z.string().nullable().optional(),
});
export type TaskCreate = z.infer<typeof TaskCreateSchema>;

export const TaskResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  path: z.string(),
  description: z.string().nullable().optional(),
});
export type TaskResponse = z.infer<typeof TaskResponseSchema>;

export const TaskListResponseSchema = z.object({
  items: z.array(TaskResponseSchema),
  total: z.number(),
});
export type TaskListResponse = z.infer<typeof TaskListResponseSchema>;

export const TaskUpdateSchema = z.object({
  name: z.string().nullable().optional(),
  type: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
});
export type TaskUpdate = z.infer<typeof TaskUpdateSchema>;

export const WorkflowCanvasStateSchema = z.object({
  nodes: z.array(z.record(z.string(), z.unknown())).optional(),
  edges: z.array(z.record(z.string(), z.unknown())).optional(),
  viewport: CanvasViewportSchema.optional(),
  selected_node_id: z.string().nullable().optional(),
  canvas_mode: z.string().optional().default("dag"),
});
export type WorkflowCanvasState = z.infer<typeof WorkflowCanvasStateSchema>;

export const WorkflowCommitCreateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
  message: z.string(),
});
export type WorkflowCommitCreate = z.infer<typeof WorkflowCommitCreateSchema>;

export const WorkflowCommitResponseSchema = z.object({
  hash: z.string(),
  message: z.string(),
});
export type WorkflowCommitResponse = z.infer<typeof WorkflowCommitResponseSchema>;

export const WorkflowCreateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
});
export type WorkflowCreate = z.infer<typeof WorkflowCreateSchema>;

export const WorkflowDeleteResponseSchema = z.object({
  id: z.string(),
  deleted: z.boolean(),
  runs_deleted: z.number(),
});
export type WorkflowDeleteResponse = z.infer<typeof WorkflowDeleteResponseSchema>;

export const WorkflowEnabledUpdateSchema = z.object({
  enabled: z.boolean(),
});
export type WorkflowEnabledUpdate = z.infer<typeof WorkflowEnabledUpdateSchema>;

export const WorkflowHealthMetricsSchema = z.object({
  run_count: z.number().optional().default(0),
  eval_pass_pct: z.number().nullable().optional(),
  eval_health: z.string().nullable().optional(),
  total_cost_usd: z.number().optional().default(0.0),
  regression_count: z.number().optional().default(0),
});
export type WorkflowHealthMetrics = z.infer<typeof WorkflowHealthMetricsSchema>;

export const WorkflowResponseSchema = z.object({
  id: z.string(),
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string().nullable().optional(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
  valid: z.boolean().optional().default(true),
  validation_error: z.string().nullable().optional(),
  block_count: z.number().optional().default(0),
  modified_at: z.number().nullable().optional(),
  enabled: z.boolean().optional().default(false),
  commit_sha: z.string().nullable().optional(),
  health: WorkflowHealthMetricsSchema.optional(),
});
export type WorkflowResponse = z.infer<typeof WorkflowResponseSchema>;

export const WorkflowListResponseSchema = z.object({
  items: z.array(WorkflowResponseSchema),
  total: z.number(),
});
export type WorkflowListResponse = z.infer<typeof WorkflowListResponseSchema>;

export const WorkflowSimulationCreateSchema = z.object({
  yaml: z.string(),
});
export type WorkflowSimulationCreate = z.infer<typeof WorkflowSimulationCreateSchema>;

export const WorkflowSimulationResponseSchema = z.object({
  branch: z.string(),
  commit_sha: z.string(),
});
export type WorkflowSimulationResponse = z.infer<typeof WorkflowSimulationResponseSchema>;

export const WorkflowUpdateSchema = z.object({
  name: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  yaml: z.string(),
  canvas_state: WorkflowCanvasStateSchema.nullable().optional(),
});
export type WorkflowUpdate = z.infer<typeof WorkflowUpdateSchema>;

export const runsight_api__transport__routers__git__LogResponseSchema = z.object({
  commits: z.array(CommitEntrySchema),
});
export type runsight_api__transport__routers__git__LogResponse = z.infer<typeof runsight_api__transport__routers__git__LogResponseSchema>;

