"""RUN-134: Generate Zod schemas from OpenAPI JSON spec."""

import json
import sys
from pathlib import Path


def openapi_type_to_zod(prop: dict, schemas: dict) -> str:
    """Convert an OpenAPI property to a Zod schema expression."""
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        return f"{ref_name}Schema"

    # anyOf (nullable / union)
    if "anyOf" in prop:
        types = prop["anyOf"]
        non_null = [t for t in types if t.get("type") != "null"]
        has_null = any(t.get("type") == "null" for t in types)
        if len(non_null) == 1:
            base = openapi_type_to_zod(non_null[0], schemas)
            return f"{base}.nullable()" if has_null else base
        # union
        parts = ", ".join(openapi_type_to_zod(t, schemas) for t in non_null)
        base = f"z.union([{parts}])"
        return f"{base}.nullable()" if has_null else base

    t = prop.get("type", "string")
    if t == "string":
        return "z.string()"
    if t == "number":
        return "z.number()"
    if t == "integer":
        return "z.number()"
    if t == "boolean":
        return "z.boolean()"
    if t == "null":
        return "z.null()"
    if t == "array":
        items = prop.get("items", {})
        return f"z.array({openapi_type_to_zod(items, schemas)})"
    if t == "object":
        if "properties" in prop:
            return generate_object_schema(prop, schemas)
        return "z.record(z.string(), z.unknown())"
    return "z.unknown()"


def generate_object_schema(schema: dict, schemas: dict) -> str:
    """Generate a z.object({...}) from an OpenAPI object schema."""
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields = []
    for name, prop in props.items():
        zod_type = openapi_type_to_zod(prop, schemas)
        if name not in required:
            zod_type = f"{zod_type}.optional()"
        if "default" in prop:
            default_val = prop["default"]
            if isinstance(default_val, bool):
                zod_type = f"{zod_type}.default({str(default_val).lower()})"
            elif isinstance(default_val, (int, float)):
                zod_type = f"{zod_type}.default({default_val})"
            elif isinstance(default_val, str):
                zod_type = f'{zod_type}.default("{default_val}")'
            elif default_val is None:
                pass  # nullable already handled
        fields.append(f"  {name}: {zod_type},")
    body = "\n".join(fields)
    return f"z.object({{\n{body}\n}})"


def schema_forbids_unknown_fields(schema: dict) -> bool:
    """Return whether an OpenAPI object schema rejects additional properties."""
    return schema.get("additionalProperties") is False


def generate_zod_file(openapi_path: str, output_path: str) -> None:
    """Generate Zod schemas TS file from OpenAPI JSON."""
    spec = json.loads(Path(openapi_path).read_text())
    schemas = spec.get("components", {}).get("schemas", {})

    lines = [
        "// Auto-generated by tools/generate-zod-schemas.py — DO NOT EDIT",
        "// Source: openapi.json (RUN-134)",
        "",
        'import { z } from "zod";',
        "",
    ]

    # Topological sort: schemas that reference others must come after them
    def get_deps(name: str) -> set[str]:
        """Extract schema names referenced via $ref."""
        s = json.dumps(schemas[name])
        deps = set()
        for part in s.split('"$ref": "#/components/schemas/'):
            if len(part) > 0 and part != s:
                ref_name = part.split('"')[0]
                if ref_name in schemas and ref_name != name:
                    deps.add(ref_name)
        return deps

    sorted_names: list[str] = []
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visited:
            return
        visited.add(name)
        for dep in get_deps(name):
            visit(dep)
        sorted_names.append(name)

    for name in sorted(schemas.keys()):
        visit(name)

    for name in sorted_names:
        schema = schemas[name]
        zod_expr = generate_object_schema(schema, schemas)
        if schema_forbids_unknown_fields(schema):
            zod_expr = f"{zod_expr}.strict()"
        lines.append(f"export const {name}Schema = {zod_expr};")
        lines.append(f"export type {name} = z.infer<typeof {name}Schema>;")
        lines.append("")

    Path(output_path).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    generate_zod_file(sys.argv[1], sys.argv[2])
