"""RUN-134: Generate Zod schemas from OpenAPI JSON spec."""

import json
import sys
from pathlib import Path


def openapi_type_to_zod(prop: dict, schemas: dict) -> str:
    """Convert an OpenAPI property to a Zod schema expression."""
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        return f"{ref_name}Schema"

    if "const" in prop:
        const_value = prop["const"]
        if isinstance(const_value, str):
            return f'z.literal("{const_value}")'
        if isinstance(const_value, bool):
            return f"z.literal({str(const_value).lower()})"
        if isinstance(const_value, (int, float)):
            return f"z.literal({const_value})"
        return "z.unknown()"

    if "enum" in prop:
        values = prop["enum"]
        if all(isinstance(value, str) for value in values):
            return "z.enum([" + ", ".join(json.dumps(value) for value in values) + "])"
        literals = []
        for value in values:
            if isinstance(value, str):
                literals.append(f"z.literal({json.dumps(value)})")
            elif isinstance(value, bool):
                literals.append(f"z.literal({str(value).lower()})")
            elif isinstance(value, (int, float)):
                literals.append(f"z.literal({value})")
        if len(literals) == 1:
            return literals[0]
        return f"z.union([{', '.join(literals)}])" if literals else "z.unknown()"

    # anyOf (nullable / union)
    if "anyOf" in prop:
        types = prop["anyOf"]
        non_null = [t for t in types if t.get("type") != "null"]
        has_null = any(t.get("type") == "null" for t in types)
        if len(non_null) == 1:
            base = openapi_type_to_zod(non_null[0], schemas)
            return f"{base}.nullable()" if has_null else base
        # union
        parts = ", ".join(openapi_type_to_zod(t, schemas) for t in non_null)
        base = f"z.union([{parts}])"
        return f"{base}.nullable()" if has_null else base

    t = prop.get("type")
    if t is None:
        if "properties" in prop or "additionalProperties" in prop:
            t = "object"
        else:
            return "z.unknown()"
    if t == "string":
        return "z.string()"
    if t == "number":
        return "z.number()"
    if t == "integer":
        return "z.number()"
    if t == "boolean":
        return "z.boolean()"
    if t == "null":
        return "z.null()"
    if t == "array":
        items = prop.get("items", {})
        return f"z.array({openapi_type_to_zod(items, schemas)})"
    if t == "object":
        if "properties" in prop:
            return generate_object_schema(prop, schemas)
        additional_properties = prop.get("additionalProperties")
        if isinstance(additional_properties, dict):
            value_schema = openapi_type_to_zod(additional_properties, schemas)
            return f"z.record(z.string(), {value_schema})"
        if additional_properties is False:
            return "z.object({}).strict()"
        return "z.record(z.string(), z.unknown())"
    return "z.unknown()"


def zod_default(default_val: object) -> str | None:
    """Return a Zod default argument for JSON-serializable OpenAPI defaults."""
    if default_val is None:
        return None
    return json.dumps(default_val)


def generate_object_schema(schema: dict, schemas: dict) -> str:
    """Generate a z.object({...}) from an OpenAPI object schema."""
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields = []
    for name, prop in props.items():
        zod_type = openapi_type_to_zod(prop, schemas)
        if name not in required:
            zod_type = f"{zod_type}.optional()"
        if "default" in prop:
            default_arg = zod_default(prop["default"])
            if default_arg is not None:
                zod_type = f"{zod_type}.default({default_arg})"
        fields.append(f"  {name}: {zod_type},")
    body = "\n".join(fields)
    zod_expr = f"z.object({{\n{body}\n}})"
    additional_properties = schema.get("additionalProperties")
    if additional_properties is False:
        zod_expr += ".strict()"
    elif additional_properties is True:
        zod_expr += ".passthrough()"
    elif isinstance(additional_properties, dict):
        catchall_schema = openapi_type_to_zod(additional_properties, schemas)
        zod_expr += f".catchall({catchall_schema})"
    return zod_expr


def generate_zod_file(openapi_path: str, output_path: str) -> None:
    """Generate Zod schemas TS file from OpenAPI JSON."""
    spec = json.loads(Path(openapi_path).read_text())
    schemas = spec.get("components", {}).get("schemas", {})

    lines = [
        "// Auto-generated by tools/generate-zod-schemas.py — DO NOT EDIT",
        "// Source: openapi.json (RUN-134)",
        "",
        'import { z } from "zod";',
        "",
    ]

    # Topological sort: schemas that reference others must come after them
    def get_deps(name: str) -> set[str]:
        """Extract schema names referenced via $ref."""
        s = json.dumps(schemas[name])
        deps = set()
        for part in s.split('"$ref": "#/components/schemas/'):
            if len(part) > 0 and part != s:
                ref_name = part.split('"')[0]
                if ref_name in schemas and ref_name != name:
                    deps.add(ref_name)
        return deps

    sorted_names: list[str] = []
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visited:
            return
        visited.add(name)
        for dep in sorted(get_deps(name)):
            visit(dep)
        sorted_names.append(name)

    for name in sorted(schemas.keys()):
        visit(name)

    for name in sorted_names:
        schema = schemas[name]
        if "enum" in schema:
            zod_expr = openapi_type_to_zod(schema, schemas)
        else:
            zod_expr = generate_object_schema(schema, schemas)
        lines.append(f"export const {name}Schema = {zod_expr};")
        lines.append(f"export type {name} = z.infer<typeof {name}Schema>;")
        lines.append("")

    Path(output_path).write_text("\n".join(lines).rstrip() + "\n")


if __name__ == "__main__":
    generate_zod_file(sys.argv[1], sys.argv[2])
